### ISSUE TITLE
Download failed several times

### ISSUE THREAD

**Issue by ApprenticeGC** [mob-sakai/unity-activate#16]
I use cli way to activate license, I am pretty sure UNITY_USERNAME, UNITY_PASSWORDand UNITY_SERIAL are given correctly. The UNITY_ULF_DIR is assigned as "/app" and Unity_vX.alf is correct(as I did this process manually to get ulf file to check)

`
node /app/dist/index.js \
    --out "$UNITY_ULF_DIR" \
    --username "$UNITY_USERNAME" \
    --password "$UNITY_PASSWORD" \
    --serial "$UNITY_SERIAL" \
    --debug \
    "/app/Unity_vX.alf"
`

I just don't know no matter how many times I try, I keep getting

Current DOM has been saved at error.html
Download failed
Run `unity-activate --help` to show help.

Unsure which part I miss. Can anyone give me a hint?

**Comment by mob-sakai** [comment]
🎉 This issue has been resolved in version 1.4.0 🎉
