### ISSUE TITLE
Seems like unity no longer allows personal license activations with manual process

### ISSUE THREAD

**Issue by StephenHodgson** [mob-sakai/unity-activate#19]
https://docs.unity3d.com/Manual/ManualActivationGuide.html

![image](https://github.com/mob-sakai/unity-activate/assets/13334553/a7130278-f431-4f40-943c-075802ecb317)

**Comment by mob-sakai** [comment]
At the moment, you can make use of it by removing the element with `style="display:none;"`.
However, its availability is uncertain for the future.
![](https://github.com/mob-sakai/unity-activate/assets/12690315/ecf2e3a8-cad8-4145-88ba-a68b17be425a)

**Comment by GhulamAliatjani** [comment]
I want to kiss  you brother. I was tried in finding how to crack it.  I follow you. thank you so much

**Comment by Chromum** [comment]
> At the moment, you can make use of it by removing the element with `style="display:none;"`. However, its availability is uncertain for the future. ![](https://private-user-images.githubusercontent.com/12690315/286144023-ecf2e3a8-cad8-4145-88ba-a68b17be425a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjYxMTEsIm5iZiI6MTcyMjgyNTgxMSwicGF0aCI6Ii8xMjY5MDMxNS8yODYxNDQwMjMtZWNmMmUzYTgtY2FkOC00MTQ1LTg4YmEtYTY4YjE3YmU0MjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAyNDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYmM1Nzc3NzY1ZTQ5Nzk4MjZjNGY3NGNhOTZiMjRhNjZlNmJhYTZmZGM5ZjhlZjQ1YjRhMTliYjE1ZWU2MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LjKSWF6S5bqetRdKFJkQVIZ3RzvPbE5DYPcU7z0xBJg) ![](https://private-user-images.githubusercontent.com/12690315/286144818-269fb84f-ada0-460f-b23a-f42afe63efeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjYxMTEsIm5iZiI6MTcyMjgyNTgxMSwicGF0aCI6Ii8xMjY5MDMxNS8yODYxNDQ4MTgtMjY5ZmI4NGYtYWRhMC00NjBmLWIyM2EtZjQyYWZlNjNlZmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAyNDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMmM4NjdjMGMxYjJiYzc4NTgwNDU1NzQ3MTgyYmNiY2Y5Y2ZkMDgwZGE5M2I4ZjNkNTkxMzE0NzNjNTU3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E52WbxoB-m0vvAmwCZXamikJWVn3GZxFy5YURnJtTFo)

Doesnt seem to work anymore unfortunatley

**Comment by StephenHodgson** [comment]
I was able to get licensing working for both pro and personal through the licensing client directly.

https://github.com/RageAgainstThePixel/activate-unity-license

**Comment by mob-sakai** [comment]
Wow, the time has finally come.

@StephenHodgson , Thank for your work!

**Comment by StephenHodgson** [comment]
> Wow, the time has finally come.
> 
> @StephenHodgson , Thank for your work!

Thank you @mob-sakai ! Love your work too.

**Comment by Gabiworld** [comment]
woa, thank you for the program!! it worked for the personal license for unity 4 :D
