### ISSUE TITLE
does this work on unity 3.x?

### ISSUE THREAD

**Issue by IceburgLettuce17** [mob-sakai/unity-activate#22]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe what help do you need**
I am wondering if this activates .ilr files.

**Additional context**
.ILR files are used on Unity 3.x

**Comment by mob-sakai** [comment]
I am not familiar with Unity 3.x activation.
This tool targets Unity 5.x and later.
