### ISSUE TITLE
"Navigation timeout of 30000 ms exceeded" when importing certain .ilf files

### ISSUE THREAD

**Issue by IceburgLettuce17** [mob-sakai/unity-activate#23]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**
The program returns a timeout error when importing a certain .ilf file.

**To Reproduce**
1. Open the program
2. Import a .ilf file
3. Wait

**Expected behavior**
The .ilf file activates successfully and can be used in Unity.

**Comment by mob-sakai** [comment]
I am not familiar with Unity 3.x activation.
This tool targets Unity 5.x and later.
