### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by jcs090218** [mob-sakai/unity-activate#5]
I got this error when trying this cli tool.

Any idea? I think it would be helpful if the tool itself print out more information about the error!

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
I installed [log4js](https://github.com/log4js-node/log4js-node) to this project :)

![image](https://user-images.githubusercontent.com/12690315/133880296-5cd9b4ab-350b-4ddd-9580-8da79896e188.png)

Btw, please try new version [v1.3.0](https://github.com/mob-sakai/unity-activate/releases/tag/v1.3.0)
